//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProje.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BookingProjectEntities : DbContext
    {
        public BookingProjectEntities()
            : base("name=BookingProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Gorevliler> Tbl_Gorevliler { get; set; }
        public virtual DbSet<Tbl_Ilceler> Tbl_Ilceler { get; set; }
        public virtual DbSet<Tbl_Kullanicilar> Tbl_Kullanicilar { get; set; }
        public virtual DbSet<Tbl_Odalar> Tbl_Odalar { get; set; }
        public virtual DbSet<Tbl_OdaTurleri> Tbl_OdaTurleri { get; set; }
        public virtual DbSet<Tbl_OtelBasvuru> Tbl_OtelBasvuru { get; set; }
        public virtual DbSet<Tbl_Oteller> Tbl_Oteller { get; set; }
        public virtual DbSet<Tbl_Puanlamalar> Tbl_Puanlamalar { get; set; }
        public virtual DbSet<Tbl_Rezervasyonlar> Tbl_Rezervasyonlar { get; set; }
        public virtual DbSet<Tbl_Sehirler> Tbl_Sehirler { get; set; }
        public virtual DbSet<Tbl_Yorumlar> Tbl_Yorumlar { get; set; }
    }
}
