//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProje.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Oteller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Oteller()
        {
            this.Tbl_Odalar = new HashSet<Tbl_Odalar>();
            this.Tbl_Puanlamalar = new HashSet<Tbl_Puanlamalar>();
            this.Tbl_Yorumlar = new HashSet<Tbl_Yorumlar>();
        }
    
        public int OtelID { get; set; }
        public Nullable<int> GorevliID { get; set; }
        public Nullable<int> İlceID { get; set; }
        public string OtelKodu { get; set; }
        public string OtelAdi { get; set; }
        public string OtelAciklamasi { get; set; }
        public string OtelTelefonu { get; set; }
        public string OtelYildizi { get; set; }
        public Nullable<bool> UcretsizWifi { get; set; }
        public byte[] OtelResmi { get; set; }
        public string AcikAdres { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Tbl_Gorevliler Tbl_Gorevliler { get; set; }
        public virtual Tbl_Ilceler Tbl_Ilceler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Odalar> Tbl_Odalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Puanlamalar> Tbl_Puanlamalar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Yorumlar> Tbl_Yorumlar { get; set; }
    }
}
