//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProje.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OtelBasvuru
    {
        public int OtelBasvuruID { get; set; }
        public string OtelAdi { get; set; }
        public string Adres { get; set; }
        public Nullable<int> IlceID { get; set; }
        public Nullable<int> OtelYildizi { get; set; }
        public Nullable<int> OdaSayisi { get; set; }
        public string GorevliAdi { get; set; }
        public string GorevliSoyadi { get; set; }
        public string GorevliEmail { get; set; }
        public string GorevliSifre { get; set; }
        public string GorevliTelefon { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Tbl_Ilceler Tbl_Ilceler { get; set; }
    }
}
