//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProje.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OdaTurleri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_OdaTurleri()
        {
            this.Tbl_Odalar = new HashSet<Tbl_Odalar>();
        }
    
        public int OdaTuruID { get; set; }
        public string OdaTuru { get; set; }
        public string OdaAciklamasi { get; set; }
        public Nullable<int> OdaKapasitesi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Odalar> Tbl_Odalar { get; set; }
    }
}
