//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProje.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Rezervasyonlar
    {
        public int RezerveOdaID { get; set; }
        public Nullable<int> KullaniciID { get; set; }
        public Nullable<int> OdaID { get; set; }
        public Nullable<int> KisiSayisi { get; set; }
        public Nullable<decimal> OdenenTutar { get; set; }
        public Nullable<System.DateTime> GirisTarihi { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Tbl_Kullanicilar Tbl_Kullanicilar { get; set; }
        public virtual Tbl_Odalar Tbl_Odalar { get; set; }
    }
}
