//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProje.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Gorevliler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Gorevliler()
        {
            this.Tbl_Oteller = new HashSet<Tbl_Oteller>();
        }
    
        public int GorevliID { get; set; }
        public string GorevliAdi { get; set; }
        public string GorevliSoyadi { get; set; }
        public string GorevliEmail { get; set; }
        public string GorevliSifre { get; set; }
        public string GorevliTelefon { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Oteller> Tbl_Oteller { get; set; }
    }
}
