//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProje.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Odalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Odalar()
        {
            this.Tbl_Rezervasyonlar = new HashSet<Tbl_Rezervasyonlar>();
        }
    
        public int OdaID { get; set; }
        public Nullable<int> OtelID { get; set; }
        public Nullable<int> OdaTuruID { get; set; }
        public Nullable<int> OdaNumarasi { get; set; }
        public Nullable<decimal> NormalOdaFiyati { get; set; }
        public Nullable<decimal> IndirimliOdaFiyati { get; set; }
        public byte[] OdaResmi { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Tbl_OdaTurleri Tbl_OdaTurleri { get; set; }
        public virtual Tbl_Oteller Tbl_Oteller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Rezervasyonlar> Tbl_Rezervasyonlar { get; set; }
    }
}
