//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingProje.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Ilceler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Ilceler()
        {
            this.Tbl_OtelBasvuru = new HashSet<Tbl_OtelBasvuru>();
            this.Tbl_Oteller = new HashSet<Tbl_Oteller>();
        }
    
        public int IlceID { get; set; }
        public string IlceAdi { get; set; }
        public Nullable<int> SehirID { get; set; }
    
        public virtual Tbl_Sehirler Tbl_Sehirler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OtelBasvuru> Tbl_OtelBasvuru { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Oteller> Tbl_Oteller { get; set; }
    }
}
